Repository cloudwalk/brlc-token, pull requests merged in 2024-02, with the labels that each got.

#61 Extend ERC20Mintable contract with premit functionality
  contracts/BRLCToken.sol
  contracts/BRLCTokenBridgeable.sol
  contracts/USJimToken.sol
  contracts/base/ERC20Freezable.sol
  contracts/base/ERC20Mintable.sol
  contracts/base/interfaces/IERC20Mintable.sol
  contracts/mocks/ERC20HookMock.sol
  contracts/mocks/base/ERC20FreezableMock.sol
  contracts/mocks/base/ERC20MintableMock.sol
  test/BRLCToken.complex.test.ts
  test/USJimToken.complex.test.ts
  test/base/ERC20Mintable.test.ts
Labels: SmartContracts

#63 Introduce ERC20Trustable base contract to remove approval step for trusted accounts
  contracts/BRLCToken.sol
  contracts/base/ERC20Base.sol
  contracts/base/ERC20Trustable.sol
  contracts/base/interfaces/IERC20Trustable.sol
  contracts/mocks/base/ERC20TrustableMock.sol
  test/BRLCToken.base.test.ts
  test/base/ERC20Freezable.test.ts
  test/base/ERC20Mintable.test.ts
  test/base/ERC20Trustable.test.ts
Labels: SmartContracts

#64 Testnet rollback maintenance
  .openzeppelin/unknown-2008.json
Labels: maintenance, smart-contract

#65 Introducing CWToken and Unifying BRL and USJim Tokens
  contracts/BRLCToken.sol
  contracts/USJimToken.sol
  contracts/base/CWToken.sol
  test/BRLCToken.test.ts
  test/USJimToken.complex.test.ts
  test/base/CWToken.complex.test.ts
  test/base/CWToken.test.ts
Labels: smart-contract

#66 Introduce balanceOfComplex function that allows to check preminted, frozen and restricted tokens in one call
  contracts/base/CWToken.sol
  contracts/base/ERC20Restrictable.sol
  contracts/base/interfaces/IERC20ComplexBalance.sol
  test/base/CWToken.complex.test.ts
Labels: smart-contract
