Repository cloudwalk/brlc-token, pull requests merged in 2025-04, with the labels that each got.

#98 feat: removing restrictions (ERC20Restrictable)
  contracts/base/CWToken.sol
  contracts/base/ERC20Restrictable.sol
  contracts/base/interfaces/IERC20ComplexBalance.sol
  contracts/base/interfaces/IERC20Restrictable.sol
  contracts/legacy/LegacyRestrictablePlaceholder.sol
  contracts/mocks/base/ERC20RestrictableMock.sol
  test/base/CWToken.complex.test.ts
  test/base/ERC20Restrictable.test.ts
Labels: smart-contract

#99 fix: `LegacyRestrictablePlaceholder` storage
  contracts/legacy/LegacyRestrictablePlaceholder.sol
Labels: smart-contract

#100 build: contract upgrade
  .openzeppelin/unknown-2008.json
  .openzeppelin/unknown-2009.json
Labels: smart-contract

#102 feat: delete `ERC20Bridgeable` contract
  .openzeppelin/goerli.json
  .openzeppelin/mainnet.json
  contracts/BRLCTokenBridgeable.sol
  contracts/base/ERC20Bridgeable.sol
  contracts/base/interfaces/IERC20Bridgeable.sol
  contracts/mocks/base/ERC20BridgeableMock.sol
  test/BRLCTokenBridgeable.test.ts
  test/base/ERC20Bridgeable.test.ts
Labels: smart-contract

#104 test: fix tests to allow them running on non-Hardhat networks
  package-lock.json
  test/BRLCToken.test.ts
  test/BRLCTokenBridgeable.test.ts
  test/USJimToken.test.ts
  test/base/CWToken.complex.test.ts
  test/base/CWToken.test.ts
  test/base/ERC20Base.test.ts
  test/base/ERC20Freezable.test.ts
  test/base/ERC20Hookable.test.ts
  test/base/ERC20Mintable.test.ts
  test/base/ERC20Trustable.test.ts
  test/base/common/PausableExtUpgradeable.test.ts
  test/base/common/RescuableUpgradeable.test.ts
  test/mocks/ERC20TokenMock.test.ts
Labels: maintenance

#103 build: contract upgrade
  .openzeppelin/unknown-2008.json
  .openzeppelin/unknown-2009.json
Labels: smart-contract

#106 build: contract upgrade
  .openzeppelin/unknown-2008.json
  .openzeppelin/unknown-2009.json
Labels: contract-upgrade

#107 fix: add the function to configure role admins
  contracts/base/ERC20Base.sol
  contracts/base/Versionable.sol
  test/base/CWToken.test.ts
  test/base/ERC20Base.test.ts
Labels: smart-contract

#108 build: contract upgrade
  .openzeppelin/unknown-2008.json
  .openzeppelin/unknown-2009.json
Labels: smart-contract
